"""LaTeX rendering & compilation service."""

from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
import tempfile
import uuid
from pathlib import Path
from typing import Any

from app.config import get_settings

logger = logging.getLogger(__name__)

settings = get_settings()
BASE = Path(__file__).resolve().parent.parent.parent  # apps/api
TEMPLATES_DIR = BASE / "templates"
STORAGE_DIR = Path(settings.STORAGE_DIR)
GENERATED_DIR = STORAGE_DIR / "generated_pdfs"

for d in (GENERATED_DIR,):
    d.mkdir(parents=True, exist_ok=True)


def latex_escape(s: Any) -> str:
    if s is None:
        return ""
    try:
        s2 = str(s)
    except Exception:
        s2 = ""
    replacements = {
        "\\": r"\\textbackslash{}",
        "%": r"\%",
        "&": r"\&",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\\textasciitilde{}",
        "^": r"\\textasciicircum{}",
        "$": r"\$",
    }
    out = s2
    for k, v in replacements.items():
        out = out.replace(k, v)
    return out


# ─── OMR marks block ────────────────────────────────────────────────
def _generate_omr_marks_block(subject: dict) -> str:
    try:
        if isinstance(subject, dict):
            markgap = float(subject.get("omr_markgap_mm", 8.0))
            markrad = float(subject.get("omr_markrad_mm", 1.8))
            crosslen = float(subject.get("omr_crosslen_mm", 3.0))
        else:
            markgap, markrad, crosslen = 8.0, 1.8, 3.0
    except Exception:
        markgap, markrad, crosslen = 8.0, 1.8, 3.0

    lines = [
        "% OMR marks inserted by server",
        "\\AddToShipoutPictureBG{%",
        "  \\begin{tikzpicture}[remember picture,overlay]",
        "    \\def\\markrad{%.2fmm}" % markrad,
        "    \\def\\crosslen{%.2fmm}" % crosslen,
        "    \\def\\markgap{%.2fmm}" % markgap,
        "",
        "    %% --- top-left: filled dot with cross ---",
        "    \\coordinate (mkTL) at ($(current page.north west)+(\\markgap,-\\markgap)$);",
        "    \\fill (mkTL) circle (\\markrad);",
        "    \\draw[line width=0.6pt] (mkTL) ++(-\\crosslen,0) -- ++(2*\\crosslen,0);",
        "    \\draw[line width=0.6pt] (mkTL) ++(0,-\\crosslen) -- ++(0,2*\\crosslen);",
        "",
        "    %% --- top-right: filled square ---",
        "    \\coordinate (mkTR) at ($(current page.north east)+(-\\markgap,-\\markgap)$);",
        "    \\fill ($(mkTR)+(-\\markrad,-\\markrad)$) rectangle ($(mkTR)+(\\markrad,\\markrad)$);",
        "",
        "    %% --- bottom-left: filled triangle ---",
        "    \\coordinate (mkBL) at ($(current page.south west)+(\\markgap,\\markgap)$);",
        "    \\fill ($(mkBL)+(0,\\markrad)$) -- ++(-1.2*\\markrad,-1.6*\\markrad) -- ++(2.4*\\markrad,0) -- cycle;",
        "",
        "    %% --- bottom-right: hollow ring ---",
        "    \\coordinate (mkBR) at ($(current page.south east)+(-\\markgap,\\markgap)$);",
        "    \\draw[line width=0.6pt] (mkBR) circle (\\markrad);",
        "    \\fill (mkBR) circle (0.5mm);",
        "  \\end{tikzpicture}%",
        "}",
    ]
    return "\n".join(lines) + "\n"


# ─── Questions TeX generator ───────────────────────────────────────
def _render_questions_tex(subject: dict) -> tuple[str, dict]:
    """Generate a TeX chunk for bubbles (column-major table layout)."""
    try:
        qs = subject.get("questions", []) if isinstance(subject, dict) else []
    except Exception:
        qs = []

    lines = ["% --- Questions block generated by server ---", "\\begin{center}", "\\begin{tikzpicture}[x=1mm,y=1mm]"]

    cols = 4
    row_h = 6.0
    bubble_d = 6.0
    bubble_gap = 4.0
    label_w = 12.0
    bubble_label_gap = 6.0
    extra_row_pad = 0.4
    start_x = 12.0
    start_y = 140.0

    if isinstance(subject, dict) and subject.get("sheet_template") in ("math_double", "default"):
        start_y = 26.0
        row_h = 6.0

    try:
        if isinstance(subject, dict):
            row_h = float(subject.get("row_h", row_h))
            label_w = float(subject.get("label_w", label_w))
            bubble_label_gap = float(subject.get("bubble_label_gap", bubble_label_gap))
            start_x = float(subject.get("start_x", start_x))
            start_y = float(subject.get("start_y", start_y))
            cols = int(subject.get("cols", cols))
    except Exception:
        pass

    PAGE_W_MM = 297.0
    PAGE_H_MM = 210.0
    SERVER_BOX_W = 0.017
    SERVER_BOX_H = 0.035

    total = len(qs)
    initial_rows_per_col = (total + cols - 1) // cols if total > 0 else 0
    max_rows_for_space = max(1, int((PAGE_H_MM - start_y - 12.0) // row_h))
    rows_per_col = min(initial_rows_per_col, max_rows_for_space)
    cols_used = (total + rows_per_col - 1) // rows_per_col if rows_per_col > 0 else 0
    col_margin_left = start_x
    col_margin_right = 20.0
    col_spacing = max(48.0, (PAGE_W_MM - col_margin_left - col_margin_right) / cols_used) if cols_used > 0 else 60.0

    meta: dict[str, Any] = {"bubbles": [], "questions": []}

    for col in range(cols_used):
        for row in range(rows_per_col):
            q_idx = col * rows_per_col + row
            if q_idx >= total:
                continue
            q = qs[q_idx]
            global_idx = None
            if isinstance(q, dict) and q.get("_global_index") is not None:
                try:
                    global_idx = int(q.get("_global_index"))
                except Exception:
                    global_idx = None
            if global_idx is None:
                global_idx = q_idx

            qx = start_x + col * col_spacing
            qy = PAGE_H_MM - start_y - (row * row_h)
            qlabel = str(q.get("label") or q.get("id") or (global_idx + 1))
            lines.append(f"  % question {global_idx + 1}")
            label_center_x = qx + (label_w / 2.0)
            lines.append(
                "  \\node[anchor=center] at (%.1f, %.1f) {\\small \\textbf{%s}.};"
                % (label_center_x, qy, latex_escape(qlabel))
            )
            vline_x = qx + label_w + (bubble_label_gap / 2.0)
            y_top = qy - (row_h / 2.0) - extra_row_pad
            y_bot = qy + (row_h / 2.0) + extra_row_pad
            left_x = qx
            lines.append(
                "  \\draw[gray!40, thin] (%.2f, %.2f) rectangle (%.2f, %.2f);"
                % (left_x, y_top, vline_x, y_bot)
            )
            lines.append(
                "  \\draw[gray!30, thin] (%.2f, %.2f) -- (%.2f, %.2f);"
                % (start_x - 6.0, y_top, PAGE_W_MM - 12.0, y_top)
            )
            lines.append(
                "  \\draw[gray!30, thin] (%.2f, %.2f) -- (%.2f, %.2f);"
                % (start_x - 6.0, y_bot, PAGE_W_MM - 12.0, y_bot)
            )

            qmeta: dict[str, Any] = {"index": global_idx, "label": qlabel, "bubbles": []}

            choices = q.get("choices") if isinstance(q.get("choices"), list) and len(q.get("choices")) > 0 else None
            if choices:
                n = len(choices)
                labels = [(c.get("label") if isinstance(c, dict) else str(i + 1)) for i, c in enumerate(choices)]
                has_geom = any(
                    (isinstance(c, dict) and (c.get("w") or c.get("h") or c.get("x") or c.get("y")))
                    for c in choices
                )
                if not has_geom:
                    q_num = int(q.get("num_choices") or subject.get("num_choices") or 0)
                    if q_num > 0:
                        BOX_W = 0.02
                        BOX_H = 0.06
                        startX = float(q.get("x_start") if q.get("x_start") is not None else (subject.get("x_start") or 0.1))
                        yv = float(q.get("y") if q.get("y") is not None else (subject.get("y") or 0.2))
                        n_val = q_num
                        start = startX
                        end = 0.9
                        span = end - start
                        step = span / max(n_val, 1)
                        gen_choices = []
                        gen_labels = []
                        for i in range(n_val):
                            cx = start + step * i + (step - BOX_W) / 2.0
                            lbl = choices[i].get("label") if i < len(choices) and isinstance(choices[i], dict) else str(i + 1)
                            gen_choices.append({"x": cx, "y": yv, "w": BOX_W, "h": BOX_H, "label": lbl})
                            gen_labels.append(gen_choices[-1]["label"])
                        choices = gen_choices
                        labels = gen_labels
                        has_geom = True
            else:
                n = int(q.get("num_choices") or subject.get("num_choices") or 4)
                labels = [str(i + 1) for i in range(n)]
                has_geom = False

            if has_geom and choices:
                use_absolute = bool(q.get("absolute_positions"))
                box_w_mm = SERVER_BOX_W * PAGE_W_MM
                reserved_margin = 0.8
                max_available_h = max(1.8, row_h - reserved_margin - 2.0 * extra_row_pad)
                desired_h = SERVER_BOX_H * PAGE_H_MM
                box_h_mm = min(desired_h, max_available_h)
                base_x = qx + label_w + bubble_label_gap if not use_absolute else 0
                for j, c in enumerate(choices):
                    if use_absolute:
                        cx_val = float(c.get("x", 0.0))
                        cy_val = float(c.get("y", 0.0))
                        cw = float(c.get("w", SERVER_BOX_W))
                        ch = float(c.get("h", SERVER_BOX_H))
                        bx = cx_val * PAGE_W_MM
                        by = cy_val * PAGE_H_MM
                        base_rx = (cw * PAGE_W_MM) / 2.0
                        base_ry = (ch * PAGE_H_MM) / 2.0
                        rx = base_rx * 0.55
                        ry = min(max(base_ry, base_rx * 1.2), box_h_mm / 2.0)
                    else:
                        bx = base_x + j * (box_w_mm + bubble_gap) + (box_w_mm / 2.0)
                        by = qy
                        base_rx = box_w_mm / 2.0
                        base_ry = box_h_mm / 2.0
                        rx = base_rx * 0.55
                        ry = min(max(base_ry, base_rx * 1.2), box_h_mm / 2.0)

                    lines.append("  \\draw[line width=0.9pt] (%.2f, %.2f) ellipse (%.2fmm and %.2fmm);" % (bx, by, rx, ry))
                    lines.append(
                        "  \\node[black!60] at (%.2f, %.2f) {\\tiny %s};"
                        % (bx, by, latex_escape(labels[j] if isinstance(labels, list) else labels))
                    )
                    qmeta["bubbles"].append(
                        {
                            "bubble_index": j,
                            "x_mm": round(float(bx), 3),
                            "y_mm": round(float(by), 3),
                            "y_mm_top": round(float(PAGE_H_MM - by), 3),
                            "x_norm": round(float(bx) / PAGE_W_MM, 6),
                            "y_norm_top": round(float((PAGE_H_MM - by) / PAGE_H_MM), 6),
                            "width_mm": round(float(rx * 2.0), 3),
                            "height_mm": round(float(ry * 2.0), 3),
                            "w_norm": round(float((rx * 2.0) / PAGE_W_MM), 6),
                            "h_norm": round(float((ry * 2.0) / PAGE_H_MM), 6),
                            "label": labels[j],
                        }
                    )
                if not use_absolute:
                    for j in range(n):
                        xcol = base_x + j * (box_w_mm + bubble_gap) + (box_w_mm / 2.0)
                        lines.append("  \\draw[gray!20, thin] (%.2f, %.2f) -- (%.2f, %.2f);" % (xcol, y_top, xcol, y_bot))
            else:
                bubble_total_w = n * bubble_d + (n - 1) * bubble_gap
                base_x = qx + label_w + bubble_label_gap
                for j in range(n):
                    bx = base_x + j * (bubble_d + bubble_gap) + (bubble_d / 2.0)
                    by = qy
                    rx_mm = (bubble_d / 2.0) * 0.45
                    ry_mm = min((bubble_d / 2.0) * 1.15, max((row_h - 0.6) / 2.0, 1.0))
                    lines.append("  \\draw[line width=0.9pt] (%.2f, %.2f) ellipse (%.2fmm and %.2fmm);" % (bx, by, rx_mm, ry_mm))
                    lines.append("  \\node[black!60] at (%.2f, %.2f) {\\tiny %s};" % (bx, by, latex_escape(labels[j])))
                    qmeta["bubbles"].append(
                        {
                            "bubble_index": j,
                            "x_mm": round(float(bx), 3),
                            "y_mm": round(float(by), 3),
                            "y_mm_top": round(float(PAGE_H_MM - by), 3),
                            "x_norm": round(float(bx) / PAGE_W_MM, 6),
                            "y_norm_top": round(float((PAGE_H_MM - by) / PAGE_H_MM), 6),
                            "width_mm": round(float(rx_mm * 2.0), 3),
                            "height_mm": round(float(ry_mm * 2.0), 3),
                            "w_norm": round(float((rx_mm * 2.0) / PAGE_W_MM), 6),
                            "h_norm": round(float((ry_mm * 2.0) / PAGE_H_MM), 6),
                            "label": labels[j],
                        }
                    )
                for j in range(n):
                    xcol = base_x + j * (bubble_d + bubble_gap) + (bubble_d / 2.0)
                    lines.append("  \\draw[gray!20, thin] (%.2f, %.2f) -- (%.2f, %.2f);" % (xcol, y_top, xcol, y_bot))

            meta["questions"].append(qmeta)

    lines.append("\\end{tikzpicture}")
    lines.append("\\end{center}")
    return "\n".join(lines), meta


def _render_questions_tex_single_block(subject: dict) -> tuple[str, dict]:
    """Render a single A4 page worth of questions."""
    try:
        qs = subject.get("questions", []) if isinstance(subject, dict) else []
    except Exception:
        qs = []

    row_h = 6.0
    start_y = 140.0
    cols = 4
    if isinstance(subject, dict) and subject.get("sheet_template") in ("math_double", "default"):
        start_y = 26.0
        row_h = 6.0
    try:
        if isinstance(subject, dict):
            row_h = float(subject.get("row_h", row_h))
            cols = int(subject.get("cols", cols))
            start_y = float(subject.get("start_y", start_y))
    except Exception:
        pass
    PAGE_H_MM = 210.0
    max_rows_for_space = max(1, int((PAGE_H_MM - start_y - 12.0) // row_h))
    capacity = max_rows_for_space * max(1, cols)
    new_qs = []
    for i, q in enumerate(qs[:capacity]):
        q2 = dict(q) if isinstance(q, dict) else {"label": str(q)}
        q2["_global_index"] = i
        new_qs.append(q2)
    subj_copy = dict(subject) if isinstance(subject, dict) else {}
    subj_copy["questions"] = new_qs
    subj_copy["cols"] = cols

    tex, meta = _render_questions_tex(subj_copy)
    if len(new_qs) < len(qs):
        note = "\n\\begin{center}\\small (表示: 先頭 %d / 全 %d 問)\\end{center}\n" % (len(new_qs), len(qs))
        tex = tex + note
        meta = dict(meta)
        meta["truncated"] = True
        meta["total_questions"] = len(qs)
        meta["shown_questions"] = len(new_qs)
    return tex, meta


# ─── TeX source rendering ─────────────────────────────────────────
def render_tex_source(subject: dict, cand_name: str = "", exam_number: str = "") -> tuple[bool, Any]:
    """Render the .tex source for a subject.

    Returns (True, (tex_source, questions_meta)) or (False, (errcode, logs)).
    """
    try:
        tmpl_map = {"default": "sheet.tex", "math_double": "sheet.math_double.tex"}
        tmpl_key = subject.get("sheet_template", "default") if isinstance(subject, dict) else "default"
        tmpl_file = tmpl_map.get(tmpl_key, "sheet.tex")
        tpl_path = TEMPLATES_DIR / tmpl_file

        if not tpl_path.exists():
            return False, ("template_missing", f"Template not found: {tpl_path}")

        content = tpl_path.read_text(encoding="utf-8")

        header_lines: list[str] = []
        if isinstance(subject, dict) and subject.get("name"):
            header_lines.append("\\renewcommand{\\SubjectName}{%s}" % latex_escape(subject.get("name")))
        if cand_name:
            header_lines.append("\\renewcommand{\\CandidateName}{%s}" % latex_escape(cand_name))
        if exam_number:
            header_lines.append("\\renewcommand{\\ExamNumber}{%s}" % latex_escape(exam_number))
        header = "\n".join(header_lines) + ("\n" if header_lines else "")

        try:
            if tmpl_key == "default":
                questions_tex, questions_meta = _render_questions_tex_single_block(subject)
            else:
                questions_tex, questions_meta = _render_questions_tex(subject)
        except Exception:
            questions_tex = "% No questions generated (error)"
            questions_meta = {"questions": [], "bubbles": []}

        try:
            marks = _generate_omr_marks_block(subject)
            if "\\begin{document}" in content:
                content = content.replace("\\begin{document}", "\\begin{document}\n" + marks, 1)
            else:
                content = marks + "\n" + content
            questions_meta = dict(questions_meta)
            questions_meta.setdefault("omr_marks", {})
            questions_meta["omr_marks"].update(
                {"markgap_mm": 8.0, "markrad_mm": 1.8, "crosslen_mm": 3.0, "shapes": ["dot+cross", "square", "triangle", "ring"]}
            )
        except Exception:
            pass

        # Insert header (\newcommand definitions) into preamble,
        # NOT before \documentclass (which would be invalid LaTeX).
        if header and "\\begin{document}" in content:
            content = content.replace("\\begin{document}", header + "\\begin{document}", 1)
        elif header:
            content = header + content

        if "%%QUESTIONS%%" in content:
            content = content.replace("%%QUESTIONS%%", questions_tex)
        elif "\\end{document}" in content:
            content = content.replace("\\end{document}", questions_tex + "\\end{document}")
        else:
            content = content + "\n" + questions_tex

        return True, (content, questions_meta)
    except Exception:
        import traceback
        return False, ("render_error", traceback.format_exc())


# ─── Compile LaTeX → PDF ──────────────────────────────────────────
def compile_latex_and_save(subject: dict, cand_name: str = "", exam_number: str = "") -> tuple[bool, Any]:
    """Compile LaTeX and save PDF. Returns (True, gid) or (False, (errcode, logs))."""
    ok, info = render_tex_source(subject, cand_name=cand_name, exam_number=exam_number)
    if not ok:
        return False, info
    tex, questions_meta = info

    with tempfile.TemporaryDirectory() as td:
        tex_path = os.path.join(td, "sheet.tex")
        with open(tex_path, "w", encoding="utf-8") as f:
            f.write(tex)

        xe_path = shutil.which("xelatex")
        if not xe_path:
            candidates = [
                "/Library/TeX/texbin/xelatex",
                "/usr/texbin/xelatex",
                "/usr/local/texlive/2025/bin/universal-darwin/xelatex",
                "/usr/local/texlive/2025/bin/x86_64-darwin/xelatex",
                "/usr/bin/xelatex",
            ]
            for p in candidates:
                if os.path.exists(p) and os.access(p, os.X_OK):
                    xe_path = p
                    break

        cmd = [xe_path or "xelatex", "-interaction=nonstopmode", "-halt-on-error", "sheet.tex"]
        try:
            logger.info("Running xelatex: %s", " ".join(cmd))
            proc = subprocess.run(cmd, cwd=td, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=90)
            out = proc.stdout.decode("utf-8", errors="replace")
            err = proc.stderr.decode("utf-8", errors="replace")
            if proc.returncode != 0:
                logs = out + "\n" + err
                logger.error("xelatex failed (rc=%d):\n%s", proc.returncode, logs[-2000:])
                return False, ("latex_failed", logs)
            pdf_path = os.path.join(td, "sheet.pdf")
            if not os.path.exists(pdf_path):
                return False, ("pdf_missing", out + "\n" + err)

            gid = uuid.uuid4().hex
            dst = GENERATED_DIR / f"{gid}.pdf"
            shutil.copyfile(pdf_path, str(dst))

            # Overlay OMR marks
            try:
                if isinstance(subject, dict) and questions_meta and questions_meta.get("omr_marks"):
                    om = questions_meta.get("omr_marks")
                    markrad = float(om.get("markrad_mm", 1.8))
                    crosslen_val = float(om.get("crosslen_mm", 3.0))
                    markgap_val = float(om.get("markgap_mm", 8.0))
                    overlay_lines = [
                        "\\documentclass[10pt]{article}",
                        "\\usepackage[a4paper,landscape,margin=0mm]{geometry}",
                        "\\usepackage{pdfpages}",
                        "\\usepackage{tikz}",
                        "\\usetikzlibrary{calc}",
                        "\\pagestyle{empty}",
                        "\\begin{document}",
                        "\\includepdf[pages=-,picturecommand={%",
                        "  \\begin{tikzpicture}[remember picture,overlay]",
                        "    \\def\\markrad{%.2fmm}" % markrad,
                        "    \\def\\crosslen{%.2fmm}" % crosslen_val,
                        "    \\def\\markgap{%.2fmm}" % markgap_val,
                        "    \\coordinate (mkTL) at ($(current page.north west)+(\\markgap,-\\markgap)$);",
                        "    \\fill (mkTL) circle (\\markrad);",
                        "    \\draw[line width=0.6pt] (mkTL) ++(-\\crosslen,0) -- ++(2*\\crosslen,0);",
                        "    \\draw[line width=0.6pt] (mkTL) ++(0,-\\crosslen) -- ++(0,2*\\crosslen);",
                        "    \\coordinate (mkTR) at ($(current page.north east)+(-\\markgap,-\\markgap)$);",
                        "    \\fill ($(mkTR)+(-\\markrad,-\\markrad)$) rectangle ($(mkTR)+(\\markrad,\\markrad)$);",
                        "    \\coordinate (mkBL) at ($(current page.south west)+(\\markgap,\\markgap)$);",
                        "    \\fill ($(mkBL)+(0,\\markrad)$) -- ++(-1.2*\\markrad,-1.6*\\markrad) -- ++(2.4*\\markrad,0) -- cycle;",
                        "    \\coordinate (mkBR) at ($(current page.south east)+(-\\markgap,\\markgap)$);",
                        "    \\draw[line width=0.6pt] (mkBR) circle (\\markrad);",
                        "    \\fill (mkBR) circle (0.5mm);",
                        "  \\end{tikzpicture}% }]{sheet.pdf}",
                        "\\end{document}",
                    ]
                    overlay_tex = os.path.join(td, "overlay.tex")
                    with open(overlay_tex, "w", encoding="utf-8") as of:
                        of.write("\n".join(overlay_lines))
                    proc2 = subprocess.run(
                        [xe_path or "xelatex", "-interaction=nonstopmode", "-halt-on-error", "overlay.tex"],
                        cwd=td, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=60,
                    )
                    overlay_pdf = os.path.join(td, "overlay.pdf")
                    if proc2.returncode == 0 and os.path.exists(overlay_pdf):
                        shutil.copyfile(overlay_pdf, str(dst))
            except Exception:
                pass

            # Save metadata JSON
            meta = {
                "subject": subject.get("name") if isinstance(subject, dict) else None,
                "candidate_name": cand_name,
                "exam_number": exam_number,
                "questions_meta": questions_meta,
            }
            meta_path = GENERATED_DIR / f"{gid}.json"
            with open(meta_path, "w", encoding="utf-8") as mf:
                json.dump(meta, mf, ensure_ascii=False, indent=2)

            return True, gid
        except FileNotFoundError:
            return False, ("xelatex_not_found", "xelatex not found. PATH=" + os.environ.get("PATH", ""))
        except subprocess.TimeoutExpired:
            return False, ("timeout", "xelatex timed out")
